import 'dart:async';

import 'package:flutter/material.dart';
import 'package:test_flutter_app/ai_chat_handler/ai_action_parser.dart';
import 'package:test_flutter_app/ai_chat_handler/conversation.dart';
import 'package:test_flutter_app/ai_chat_handler/message.dart';
import 'package:test_flutter_app/ai_chat_handler/message_database.dart';
import 'package:test_flutter_app/ai_chat_handler/ai_response.dart';

class AIChatPage extends StatefulWidget {
  const AIChatPage({
      super.key,
      this.conversationId,
      this.onConversationCreated,
      this.onConversationDeleted,
      this.onTodoAction,
      this.onCalendarAction,
  });
  final Future<void> Function(int)? onConversationCreated; // callback function to notify the parent widget when a conversation is updated (e.g., when a new message is added or a conversation is created)
  final Future<void> Function(int)? onConversationDeleted; // callback function to notify the parent widget when a conversation is deleted, passing the id of the deleted conversation as an argument
  final VoidCallback? onTodoAction; // callback function to notify the parent widget when a to-do action is parsed from the AI's response, passing the action as an argument
  final VoidCallback? onCalendarAction; // callback function to notify the parent widget when a calendar action is parsed from the AI's response, passing the action as an argument
  final int? conversationId;

  @override
  State<AIChatPage> createState() => AIChatPageState();
}

class AIChatPageState extends State<AIChatPage> {
  List<Message> messages = []; // this will hold the chat messages
  // int? currentConversationId; // to keep track of the current conversation
  List<Map<String, String>> messageHistModified = []; // this will hold the modified message history in the format expected by the Ollama API (a list of maps with "role" and "content" keys)

  final TextEditingController textController = TextEditingController(); // controller for the TextField
  final ScrollController scrollController = ScrollController(); // for scrolling the ListView to the bottom when a new message is added
  
  final AIqueryHandler aiQueryHandler = AIqueryHandler(); // instance of the AI query handler

  Future<void> loadMessages(int? currentConversationId) async {
    if (currentConversationId == -1 || currentConversationId == null) {
      setState(() {
        this.messages = []; // clear messages if no conversation is selected
        messageHistModified = []; // clear the modified message history if no conversation is selected
      });
      return;
    }
    final messages = await MessageDatabase.getMessage(currentConversationId);
    setState(() {
      this.messages = messages;
      messageHistModified = messages.map((message) => <String, String>{
        'role': message.isUser ? 'user' : 'assistant', // determine the role based on the isUser attribute of the Message object
        'content': message.text, // use the text attribute of the Message object as the content of the message
      }).toList(); // convert the list of Message objects into the format expected by the Ollama API and update the modified message history
    }); 
  }

  Future<int> createNewConversation(String title) async {
    final conversation = Conversation(
      // id will be auto-generated by the database
      title: title,
      timestamp: DateTime.now(),
    );
    final conversationId = await MessageDatabase.addConversation(conversation);
    // currentConversationId = conversationId; // set the current conversation to the newly created one
    return conversationId;
    // setState(() {
    // });
  }

  Future<void> createMessage(String text, int conversationId, bool isUser) async {
    await MessageDatabase.addMessage(
      Message(
        id: null, // id will be auto-generated by the database
        conversationId: conversationId,
        text: text, // this should be set to the text from the TextField
        timestamp: DateTime.now(), // this will be set to the current time
        isUser: isUser,
      )
    );
    // await loadMessages(currentConversationId ?? -1); // reload messages to include the new message - using -1 as a placeholder for no conversation
  }

    Future<Map<String, String>> mapMessage(List<Map<String, String>> messageHistModified, List<Message> messageHistory) async {
    Message lastMessage = messageHistory.last; // get the last message from the message history
    Map<String, String> modifiedMessage = <String, String>{
      'role': lastMessage.isUser ? 'user' : 'assistant', // determine the role based on the isUser attribute of the Message object
      'content': lastMessage.text, // use the text attribute of the Message object as the content of the message
    };
    
    return modifiedMessage;
  }

  Future<void> generateTitleAsync(String firstMessage, int conversationId) async {
    String title = "";
    await aiQueryHandler.streamAIResponse(
      messageHistory: [{
        'role': 'user',
        'content': 'Generate a concise title for a conversation based on the following message: ${textController.text} within no more than 7 words, and WITHOUT any <ACTION> block.'
      }],
      onToken: (token) async {
        setState(() {
          title += token; // append each token to the title as it arrives                        
        });
      }, 
      onDone: () async {
        title = title.trim(); // trim any extra whitespace from the generated title
        // update the conversation title in the database
        await MessageDatabase.updateConversationTitle(conversationId, title);
        await widget.onConversationCreated?.call(conversationId); // notify the parent widget that a new conversation has been created and the title has been generated, passing the conversationId as an argument
      }
    );
  }

  Future<bool?> showActionConfirmationDialog(Map<String, dynamic> action) async {
  final type = action['action'] as String? ?? '';
  final payload = action['payload'] as Map<String, dynamic>? ?? {};

  String title;
  String summary;

  switch (type) {
    case 'create_calendar_event':
      title = 'Create Calendar Event?';
      final start = payload['start'] ?? '?';
      final end = payload['end'] ?? '?';
      final desc = (payload['description'] as String?) ?? '';
      summary = 'Title: ${payload['title'] ?? '?'}\nFrom: $start\nTo: $end${desc.isNotEmpty ? '\nDescription: $desc' : ''}';
      break;
    case 'create_todo_list':
      title = 'Create To-Do List?';
      final items = (payload['items'] as List<dynamic>?)
          ?.map((e) => '• $e')
          .join('\n') ?? 'No items';
      summary = 'Title: ${payload['title'] ?? '?'}\n$items';
      break;
    case 'create_todo_item':
      title = 'Add Task?';
      summary = 'Add "${payload['description'] ?? '?'}" '
          'to list "${payload['listTitle'] ?? '?'}"';
      break;
    default:
      title = 'Confirm Action';
      summary = 'Unknown action: $type';
  }

  return showDialog<bool>(
    context: context,
    barrierDismissible: false,
    builder: (_) => AlertDialog(
      title: Text(title),
      content: Text(summary),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context, false),
          child: const Text('Cancel'),
        ),
        ElevatedButton(
          onPressed: () => Navigator.pop(context, true),
          child: const Text('Confirm'),
        ),
      ],
    ),
  );
}

  @override
  void initState() {
    super.initState();
    loadMessages(widget.conversationId ?? -1); // load messages for the current conversation (if it exists) - using -1 as a placeholder for no conversation
    // loadConversations();
  }

  @override
  void didUpdateWidget(covariant AIChatPage oldWidget) {
    super.didUpdateWidget(oldWidget);

    // if (widget.conversationId != oldWidget.conversationId) {
    //   currentConversationId = widget.conversationId;
    //   print(widget.conversationId);
    //   if (widget.conversationId == null) {
    //     currentConversationId = null;
    //     setState(() {
    //       messages = [];
    //     });
    //   } else {
    //     loadMessages(currentConversationId ?? -1);
    //   }      
    // }
    if (widget.conversationId != oldWidget.conversationId) {
      loadMessages(widget.conversationId ?? -1); // load messages for the new conversation when the conversationId changes (using -1 as a placeholder for no conversation)
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Expanded(
          child: ListView.builder(
            controller: scrollController,
            itemCount: messages.length,
            itemBuilder: (context, index) {
              return Align(
                alignment: messages[index].isUser ? Alignment.topRight : Alignment.topLeft, // Aligns messages to the left
                child: Container(
                  margin: const EdgeInsets.symmetric(vertical: 4.0, horizontal: 8.0),
                  padding: const EdgeInsets.all(12.0),
                  decoration: BoxDecoration(
                    color: messages[index].isUser ? Colors.blue[300] : Colors.grey[300],
                    borderRadius: BorderRadius.circular(8.0),
                  ),
                  child: Text(messages[index].text),
                ),
              );
            },
          )
        ),
        
        Padding(
          padding: const EdgeInsets.all(8.0),
          child: Row(
            children: [
              IconButton(
                onPressed: (){},
                icon: const Icon(Icons.add_circle),
              ),
              Expanded(
                child: TextField(
                  controller: textController, // connect the TextField to the controller
                  decoration: InputDecoration(
                    hintText: 'Ask [app_name] anything...',
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(8.0),
                    ),
                  ),
                ),
              ),
              IconButton(
                onPressed: () async {
                  int? conversationId = widget.conversationId;
                  if (textController.text.trim().isEmpty) return; // don't send empty messages 
                  if (widget.conversationId == null) {
                    messageHistModified.clear(); // clear the modified message history when starting a new conversation
                    messages.clear(); // clear the messages list when starting a new conversation                    
                    String title = "new Conversation";
                    
                    conversationId = await createNewConversation(title); // creates a conversation and updates currentConversationId to the new conversation's id
                    await widget.onConversationCreated?.call(conversationId);
                    generateTitleAsync(textController.text, conversationId); // generate a title for the new conversation based on the first message and update the conversation title in the database
                  } 
                  await createMessage(textController.text, conversationId!, true);
                  await loadMessages(conversationId); // reload messages from the database to include the new message - for displaying as well 
                  // await loadConversations(); // reload conversations to update the timestamp of the current conversation - for displaying in the sidebar
                  textController.clear(); // clear the TextField after sending the message
                  
                  // convert the latest user messasge into proper AI query format & add it to the message history for the Ollama API
                  Map<String, String> modifiedMessage = await mapMessage(messageHistModified, messages);
                  messageHistModified.add(modifiedMessage); // add the modified message to the message history in the format expected by the Ollama API
                  
                  // get AI response using the modified message history and create a new message in the database for the AI's response, then reload messages to display the AI's response
                  // String aiResponse = await aiQueryHandler.getAIResponse(messageHistModified, conversationId);
                  String fullResponse = "";
                  await createMessage(fullResponse, conversationId, false); // add a new message to the messages list for the AI's response - this will be updated as the response is streamed in
                  await loadMessages(conversationId); 

                  await aiQueryHandler.streamAIResponse(
                    messageHistory: messageHistModified, 
                    onToken: (token) async {
                      fullResponse += token; 

                      setState(() {
                        messages[messages.length-1] = messages[messages.length-1].copyWith(
                          text: fullResponse,
                          conversationId: conversationId, 
                          isUser: false, 
                          timestamp: DateTime.now()); // update the last message in the messages list with the new token as it arrives, and set isUser to false to indicate that it's an AI response
                      }); // update the UI to display the new token as it arrives  
                    }, 
                    onDone: () async {
                      final parsed = AIActionParser.parse(fullResponse); // parse the AI's response to check for any embedded actions
                      final displayText = parsed.action != null? parsed.cleanText : fullResponse; // if an action is parsed, use the clean text without the action block for display; otherwise, use the full response

                      setState(() {
                        messages[messages.length-1] = messages[messages.length-1].copyWith(
                          text: parsed.cleanText, // update the last message in the messages list to remove the action block from the displayed text
                        );
                      });

                      await MessageDatabase.updateMessage(
                        messages[messages.length-1].id!, // update the last message in the database with the clean text for display (removing the action block if it exists)
                        displayText,
                      );

                      if (parsed.action != null) { 
                        final confirmed = await showActionConfirmationDialog(parsed.action!); // if an action is parsed, show a confirmation dialog to the user with the details of the action and ask for confirmation before executing it
                          if (confirmed == true){
                            final actionType = await AIActionParser.execute(parsed.action!); // execute the parsed action and get the type of action that was executed (e.g., "todo_list_added" or "calendar_event_added")
                            if (actionType != null && actionType.contains('todo')) widget.onTodoAction?.call();
                            if (actionType != null && actionType.contains('calendar')) widget.onCalendarAction?.call();          
                          } 

                      }
                    });

                  // await createMessage(aiResponse, conversationId, false); // create a new message in the database for the AI's response
                  await loadMessages(conversationId); // reload messages to include the AI's response
                  
                  // add AI response to the message history for the Ollama API
                  Map<String, String> modifiedResponse = await mapMessage(messageHistModified, messages);
                  messageHistModified.add(modifiedResponse); // add the AI's response to the message history in the format expected by the Ollama API

                  // setState(() {
                  // });

                },
                icon: const Icon(Icons.send),
              ),
            ],
          ),
        ),
      
      
      ],
    );

    // return Stack(
    //   children: [
        
    //   ],
    // );
  }
}