import 'package:flutter/material.dart';
import 'package:test_flutter_app/ai_chat_handler/conversation.dart';
import 'package:test_flutter_app/ai_chat_handler/message.dart';
import 'package:test_flutter_app/ai_chat_handler/message_database.dart';
import 'package:test_flutter_app/ai_chat_handler/ai_response.dart';

class AIChatPage extends StatefulWidget {
  const AIChatPage({super.key});

  @override
  State<AIChatPage> createState() => AIChatPageState();
}

class AIChatPageState extends State<AIChatPage> {
  List<Message> messages = []; // this will hold the chat messages
  List<Conversation> conversations = []; // this will hold the list of conversations (for the sidebar)
  int? currentConversationId; // to keep track of the current conversation

  final TextEditingController textController = TextEditingController(); // controller for the TextField
  final ScrollController scrollController = ScrollController(); // for scrolling the ListView to the bottom when a new message is added
  

  Future<void> loadMessages(int currentConversationId) async {
    if (currentConversationId == -1) {
      setState(() {
        this.messages = []; // clear messages if no conversation is selected
      });
      return;
    }
    final messages = await MessageDatabase.getMessage(currentConversationId);
    setState(() {
      this.messages = messages; 
    });
  }

  Future<void> loadConversations() async {
    final conversations = await MessageDatabase.getConversations();
    setState(() {
      this.conversations = conversations; 
    });
  }

  Future<void> createNewConversation(String title) async {
    final conversation = Conversation(
      // id will be auto-generated by the database
      title: title,
      timestamp: DateTime.now(),
    );
    final conversationId = await MessageDatabase.addConversation(conversation);
    setState(() {
      currentConversationId = conversationId; // set the current conversation to the newly created one
    });
  }

  Future<void> deleteConversation(int conversationId) async {
    if (conversationId == -1) {
      return; // do nothing if no conversation is selected
    }
    await MessageDatabase.deleteConversation(conversationId);
    loadConversations(); // reload conversations to update the sidebar after deletion
    if (currentConversationId == conversationId) {
      setState(() {
        currentConversationId = (conversations.isNotEmpty ? conversations.length-1 : 0); // reset current conversation if it was deleted
        loadMessages(currentConversationId ?? -1);// clear messages from the UI
      });
    }
  }

  @override
  void initState() {
    super.initState();
    loadMessages(currentConversationId ?? -1); // load messages for the current conversation (if it exists) - using -1 as a placeholder for no conversation
    loadConversations();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Expanded(
          child: ListView.builder(
            controller: scrollController,
            itemCount: messages.length,
            itemBuilder: (context, index) {
              return Align(
                alignment: messages[index].isUser ? Alignment.topRight : Alignment.topLeft, // Aligns messages to the left
                child: Container(
                  margin: const EdgeInsets.symmetric(vertical: 4.0, horizontal: 8.0),
                  padding: const EdgeInsets.all(12.0),
                  decoration: BoxDecoration(
                    color: messages[index].isUser ? Colors.blue[300] : Colors.grey[300],
                    borderRadius: BorderRadius.circular(8.0),
                  ),
                  child: Text(messages[index].text),
                ),
              );
            },
          )
        ),
        
        Padding(
          padding: const EdgeInsets.all(8.0),
          child: Row(
            children: [
              Expanded(
                child: TextField(
                  controller: textController, // connect the TextField to the controller
                  decoration: InputDecoration(
                    hintText: 'Ask [app_name] anything...',
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(8.0),
                    ),
                  ),
                ),
              ),
              IconButton(
                onPressed: () async {
                  if (currentConversationId == null) {
                    await createNewConversation('New Conversation'); // create a new conversation, add it to the database and get its ID 
                  } 
                  await MessageDatabase.addMessage( 
                    Message(
                      id: null, // id will be auto-generated by the database
                      conversationId: currentConversationId!, 
                      text: textController.text, // this should be set to the text from the TextField
                      title: 'User message', // this can be the same as text or a summary of it
                      timestamp: DateTime.now(), // this should be set to the current time
                      isUser: true,
                    )
                  );

                  final updatedMessages = await MessageDatabase.getMessage(currentConversationId!); // reload messages from the database to include the new message
                  final updatedConversations = await MessageDatabase.getConversations(); // reload conversations to update the timestamp of the current conversation
                  setState(() {
                    // messages.add(Message(
                    //   id: null, // id will be auto-generated by the database
                    //   conversationId: currentConversationId!, // this should be set to the current conversation's ID
                    //   text: textController.text, // this should be set to the text from the TextField
                    //   title: 'User message', // this can be the same as text or a summary of it
                    //   timestamp: DateTime.now(), // this should be set to the current time
                    //   isUser: true,
                    // ));
                    messages = updatedMessages; // reload messages from the database to include the new message - for displaying as well
                    conversations = updatedConversations; // reload conversations to update the timestamp of the current conversation - for displaying in the sidebar
                    textController.clear(); // clear the TextField after sending the message
                  });

                },
                icon: const Icon(Icons.send),
              ),
            ],
          ),
        ),
      
      
      ],
    );

    // return Stack(
    //   children: [
        
    //   ],
    // );
  }
}